defaults:
  - global: qwen2_5_omni
  - data@data_dict: spoofing
  - override hydra/job_logging: none
  - _self_

exp_dir: Null
ckpt_dir: Null

test_dataloader:
  _target_: torch.utils.data.DataLoader
  dataset: ${data_dict.test}
  batch_size: 1
  num_workers: 12
  collate_fn:
    _target_: qwenvl.data.data_qwen.OmniCollator
    torchify_keys:
      - video_second_per_grid
      - spoof_embeds

unused_items:
  - keywords

max_new_tokens: 1024
do_sample: false
num_sample: 1
output_fname: inference.json

hydra:
  output_subdir: null
  run:
    dir: .
