data_format: "json"
train_type: "sft"
model_type: qwen2.5omni
pretrained_ckpt: /path/to/checkpoints/Qwen2.5-Omni-7B
processor:
  _target_: qwenvl.data.processing_qwen2_5_omni.Qwen2_5OmniProcessor.from_pretrained
  pretrained_model_name_or_path: ${..pretrained_ckpt}
petrel_oss_config: /path/to/petreloss.conf
train_dataset_max_samples: Null
val_dataset_max_samples: 1000
